### ISSUE TITLE
CR-14: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;

### ISSUE THREAD

**Issue by tartarJR** [tartarJR/Currencify#17]
Refer to the accepted answer to this Stackoverflow question for the reason of the issue:
https://stackoverflow.com/questions/51782548/androidxappcompat-iart-error-android-view-viewonunhandledkeyeventlistener/52954286#52954286

**Comment by Berdugo1994** [comment]
I had the same problem.. what did help me is to update dependency to androidx.appcompat:appcompat:1.3.0-alpha02

**Comment by SamiranKumar** [comment]
Solved the issue for me.

build.gradle (app level)
**//Adding dependency** 
`implementation 'androidx.core:core:1.5.0-alpha04'`

**Comment by onyxius** [comment]
> implementation 'androidx.core:core:1.5.0-alpha04'

Thank you for this.  Does it hurt to have 2 of them but with different versions?  
Here is my dependencies.

implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    **implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.core:core-ktx:1.6.0-alpha01'**
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
